on:
  push:
    branches: ['master']

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn build
        env:
          NODE_ENV: production

      - name: Test
        run: yarn test
        env:
          NODE_ENV: production
          HOP_TOKEN: ${{ secrets.HOP_TOKEN }}

      - name: Check we have changesets since master
        run: yarn changeset status --since=master

      - name: Bump version
        run: yarn changeset version

      - name: Publish to npm
        uses: changesets/action@v1
        with:
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit changes
        continue-on-error: true
        run: |
          git config --global user.email "ci@hop.io"
          git config --global user.name "Hop CI"
          git add .
          git commit -m "Bump version"
          git push -u --set-upstream origin master --force
